#pragma once

#define CI_LAY_BASE 0
#define CI_LAY_NUMSYM 1
#define CI_LAY_NAVI 2
#define CI_LAY_LOL 3
#define CI_LAY_WASD 4

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  // BASE
  [0] = LAYOUT_split_3x6_3_ex2(KC_BSLS,KC_Q,KC_W,KC_F,KC_P,KC_B,DF(CI_LAY_WASD),KC_NO,KC_J,KC_L,KC_U,KC_Y,KC_MINUS,KC_EQUAL,KC_LBRC,KC_A,KC_R,KC_S,KC_T,KC_G,DF(CI_LAY_LOL),KC_NO,KC_M,KC_N,KC_E,KC_I,KC_O,KC_RBRC,KC_QUOTE,KC_Z,KC_X,KC_C,KC_D,KC_V,KC_K,KC_H,KC_COMMA,KC_DOT,KC_SLASH,KC_SCLN,LGUI_T(KC_ESC),LT(1,KC_TAB),LCTL_T(KC_ENTER),LSFT_T(KC_SPC),LT(2,KC_BSPC),LALT_T(KC_DEL)),

  // NUMSYM
  [1] = LAYOUT_split_3x6_3_ex2(KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_7,KC_8,KC_9,KC_NO,KC_NO,LSFT(KC_9),LSFT(KC_5),LSFT(KC_6),LSFT(KC_7),LSFT(KC_8),KC_NO,KC_NO,KC_NO,KC_NO,KC_4,KC_5,KC_6,KC_0,LSFT(KC_0),KC_GRAVE,LSFT(KC_1),LSFT(KC_2),LSFT(KC_3),LSFT(KC_4),KC_NO,KC_NO,KC_1,KC_2,KC_3,KC_DOT,KC_ENTER,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS),

  // NAVI
  [2] = LAYOUT_split_3x6_3_ex2(KC_NO,KC_F9,KC_F10,KC_F11,KC_F12,KC_NO,KC_TRNS,KC_TRNS,MC_4,MC_0,MC_1,MC_2,MC_3,MC_5,LSFT(KC_9),KC_F5,KC_F6,KC_F7,KC_F8,KC_NO,KC_TRNS,KC_TRNS,KC_NO,KC_LEFT,KC_DOWN,KC_UP,KC_RIGHT,LSFT(KC_0),KC_NO,KC_F1,KC_F2,KC_F3,KC_F4,KC_NO,KC_NO,KC_HOME,KC_PGDN,KC_PGUP,KC_END,KC_NO,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS),

  // LOL
  [3] = LAYOUT_split_3x6_3_ex2(KC_ESC,KC_1,KC_2,KC_3,KC_4,KC_5,KC_6,KC_F1,KC_NO,KC_F9,KC_F10,KC_F11,KC_F12,KC_NO,KC_TAB,KC_Q,KC_W,KC_E,KC_R,KC_T,KC_Y,KC_F2,KC_NO,KC_F5,KC_F6,KC_F7,KC_F8,KC_NO,KC_SPC,KC_A,KC_S,KC_D,KC_F,KC_G,KC_NO,KC_F1,KC_F2,KC_F3,KC_F4,KC_NO,KC_LALT,KC_LSFT,KC_LCTL,DF(0),KC_NO,KC_NO),

  // WASD
  [4] = LAYOUT_split_3x6_3_ex2(KC_ESC,KC_GRAVE,KC_Q,KC_W,KC_E,KC_R,KC_T,KC_NO,KC_NO,KC_F9,KC_F10,KC_F11,KC_F12,KC_NO,KC_TAB,KC_LSFT,KC_A,KC_S,KC_D,KC_F,KC_G,KC_NO,KC_NO,KC_F5,KC_F6,KC_F7,KC_F8,KC_NO,KC_LCTL,KC_LALT,KC_Z,KC_X,KC_C,KC_V,KC_NO,KC_F1,KC_F2,KC_F3,KC_F4,KC_NO,KC_SPC,KC_SPC,KC_SPC,DF(0),KC_NO,KC_NO)
};